# Generated by Django 5.0.2 on 2024-05-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='GradingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('grading_type', models.CharField(choices=[('relative', 'Relative'), ('absolute', 'Absolute'), ('manual', 'Manual')], max_length=10)),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='pdf.pdffile')),
            ],
        ),
    ]
