# Generated by Django 5.0.2 on 2024-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_pdffile_uploaded_at_gradingcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingcriteria',
            name='absolute_criteria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingcriteria',
            name='manual_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradingcriteria',
            name='relative_criteria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingcriteria',
            name='word_range',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gradingcriteria',
            name='grading_type',
            field=models.CharField(choices=[('relative', 'Relative'), ('absolute', 'Absolute'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gradingcriteria',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
